"""
Billing invoice generator for the UBI POC.
Generates invoice JSON and CSV files under artifacts/invoices/.
"""
import os
import json
import csv
from datetime import datetime, timedelta
from typing import Dict

ARTIFACTS_DIR = os.path.join(os.path.dirname(__file__), 'artifacts')
INVOICES_DIR = os.path.join(ARTIFACTS_DIR, 'invoices')

os.makedirs(INVOICES_DIR, exist_ok=True)


def _next_invoice_id():
    # simple timestamp-based id
    return 'INV-' + datetime.utcnow().strftime('%Y%m%d%H%M%S')


def generate_invoice(driver_id: str, period: str, premium_breakdown: Dict) -> Dict:
    """Generate invoice JSON and CSV and return invoice dict with paths.

    period: string like '2026-08'
    premium_breakdown: dict from pricing.compute_premium
    """
    invoice_id = _next_invoice_id()
    due_date = (datetime.utcnow() + timedelta(days=30)).date().isoformat()

    invoice = {
        'invoice_id': invoice_id,
        'driver_id': driver_id,
        'period': period,
        'base_premium': premium_breakdown.get('base_premium'),
        'risk_adj_pct': premium_breakdown.get('risk_adj_pct'),
        'mileage_adj_pct': premium_breakdown.get('mileage_adj_pct'),
        'ev_adj_pct': premium_breakdown.get('ev_adj_pct'),
        'safe_adj_pct': premium_breakdown.get('safe_adj_pct'),
        'premium_before_tax': premium_breakdown.get('premium_before_tax'),
        'tax_pct': premium_breakdown.get('tax_pct'),
        'tax': premium_breakdown.get('tax'),
        'total_due': premium_breakdown.get('total_due'),
        'due_date': due_date,
        'generated_at': datetime.utcnow().isoformat() + 'Z'
    }

    json_path = os.path.join(INVOICES_DIR, f"{invoice_id}.json")
    csv_path = os.path.join(INVOICES_DIR, f"{invoice_id}.csv")

    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(invoice, f, indent=2)

    # write a simple CSV line with header
    with open(csv_path, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(list(invoice.keys()))
        writer.writerow([invoice[k] for k in invoice.keys()])

    invoice['json_path'] = json_path
    invoice['csv_path'] = csv_path

    # Attempt to create a simple PDF invoice using reportlab if available
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.units import mm
        from reportlab.pdfgen import canvas

        pdf_path = os.path.join(INVOICES_DIR, f"{invoice_id}.pdf")
        c = canvas.Canvas(pdf_path, pagesize=A4)
        width, height = A4
        margin = 20 * mm
        y = height - margin

        # Header
        c.setFont('Helvetica-Bold', 16)
        c.drawString(margin, y, f"Invoice: {invoice_id}")
        c.setFont('Helvetica', 10)
        c.drawString(margin, y - 18, f"Driver ID: {driver_id}")
        c.drawString(margin + 300, y - 18, f"Period: {period}")
        c.drawString(margin + 300, y - 32, f"Due date: {due_date}")
        y -= 54

        # Line items / breakdown
        c.setFont('Helvetica-Bold', 12)
        c.drawString(margin, y, 'Premium breakdown')
        y -= 16
        c.setFont('Helvetica', 10)
        rows = [
            ('Base premium', f"{invoice.get('base_premium')}") ,
            ('Risk adj (%)', f"{invoice.get('risk_adj_pct')}") ,
            ('Mileage adj (%)', f"{invoice.get('mileage_adj_pct')}") ,
            ('EV adj (%)', f"{invoice.get('ev_adj_pct')}") ,
            ('Safe adj (%)', f"{invoice.get('safe_adj_pct')}") ,
            ('Premium before tax', f"{invoice.get('premium_before_tax')}") ,
            ('Tax (%)', f"{invoice.get('tax_pct')}") ,
            ('Tax', f"{invoice.get('tax')}") ,
            ('Total due', f"{invoice.get('total_due')}") ,
        ]
        for label, val in rows:
            c.drawString(margin, y, label)
            c.drawRightString(width - margin, y, str(val))
            y -= 14
            if y < margin + 50:
                c.showPage()
                y = height - margin

        # Footer
        c.setFont('Helvetica-Oblique', 8)
        c.drawString(margin, margin + 10, 'This is a demo invoice generated by the UBI POC. Not a tax invoice.')
        c.save()
        invoice['pdf_path'] = pdf_path
    except Exception as _e:
        invoice['pdf_error'] = f'PDF generation skipped or failed: {_e}'

    return invoice


if __name__ == '__main__':
    # quick smoke
    from pricing import compute_premium
    pb = compute_premium(risk_score=80, monthly_mileage=1200, is_ev=False, safe_driver=False)
    inv = generate_invoice('driver_001', '2026-08', pb)
    print('Invoice generated:', inv['invoice_id'], inv['json_path'])
